--USE MASTER
--GO
--IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME='QLSANPHAM')
	DROP DATABASE QLSanPham
CREATE DATABASE QLSANPHAM
ON (NAME='QLSANPHAM_DATA',FILENAME='G:\QLSANPHAM.MDF')
LOG ON (NAME='QLSANPHAM_LOG',FILENAME='G:\QLSANPHAM.LDF')
GO
USE [QLSanPham] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE TABLE [dbo].[LOAISP](
 	[MALOAI] [CHAR] (2) NOT NULL, 
 	[TENLOAI] [NVARCHAR](30) NULL, 
 CONSTRAINT [PK_dbo.LOAISP] PRIMARY KEY CLUSTERED( 
 	[MALOAI] ASC 
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, 
ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY] 
) ON [PRIMARY] 

GO 
/****** Object:  Table [dbo].[Student]    Script Date: 10/07/2019 20:59:08 ******/ SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

CREATE TABLE [dbo].[SANPHAM]( 
 	[MASP] [CHAR](6) NOT NULL, 
 	[TENSP] [nvarchar](30) NULL, 
 	[NGAYNHAP] [DATETIME] NULL, 
 	[MALOAI] [CHAR] (2)NULL, 
 CONSTRAINT [PK_dbo.SANPHAM] PRIMARY KEY CLUSTERED  ( 
 	[MASP] ASC 
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, 
ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO 
/****** Object:  ForeignKey [FK_Student_Faculty]    Script Date: 10/07/2019 20:59:08 ******/ 
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_SANPHAM_LOAISP] FOREIGN KEY([MALOAI]) 
REFERENCES [dbo].[LOAISP] ([MALOAI])
 GO 
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_SANPHAM_LOAISP] 
GO