

DROP DATABASE QLSanPham
CREATE DATABASE QLSanPham
USE [QLSanPham] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[LOAISP]( 
 	[MALOAI] [nvarchar](2) NOT NULL, 
 	[TenLoai] [nvarchar](30) NULL, 
 CONSTRAINT [PK_dbo.LOAISP] PRIMARY KEY CLUSTERED  
( 
 	[MALOAI] ASC 
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, 
ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO 
 SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[SANPHAM]( 
 	[MASP] [char](6) NOT NULL, 
 	[TENSP] [nvarchar](20) NULL, 
 	[NGAYNHAP] [DateTime] NULL, 
 	[MALOAI] [char](2) NULL, 
 CONSTRAINT [PK_dbo.SANPHAM] PRIMARY KEY CLUSTERED  ( 
 	[MASP] ASC 
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, 
ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO 
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_SANPHAM_LOAISP] FOREIGN KEY([MALOAI]) 
REFERENCES [dbo].[LOAISP] ([MALOAI])
 GO 
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_SANPHAM_LOAISP] 
GO


SELECT * FROM LOAISP
INSERT INTO LOAISP VALUES('01', 'Bánh kẹo')
INSERT INTO LOAISP VALUES('02', 'Giải khát')
GO

SELECT * FROM SANPHAM
INSERT INTO SANPHAM VALUES('SP0001','Bánh Quy Bơ Sữa', 08/20/2014,'Bánh kẹo')
INSERT INTO SANPHAM VALUES('SP0002','Bánh Quy Kịp Thịt', 05/24/2014, 'Bánh kẹo')
INSERT INTO SANPHAM VALUES('SP0003','Bialon 333', 04/20/2014, 'Giải khát')
GO
